stages:
  - build
  - deploy

image: moreillon/ci-dind
services:
  - name: docker:19.03.12-dind


variables:
  APPLICATION_NAME: weight
  CONTAINER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_SHORT_SHA}
  CERTIFICATE_DOMAIN: api.weight.maximemoreillon.com


build:
  stage: build
  only:
    - master
  tags:
    - dind
  script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin;
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag  ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_TAGGED}
    - docker image rm ${CONTAINER_IMAGE}
    - docker image rm ${CONTAINER_IMAGE}

deploy:
  stage: deploy
  only:
    - master
  tags:
    - dind
  script:
    - envsubst < manifest.yml | kubectl apply -f -
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
