stages:
  - build
  - deploy

image: docker:24.0.5
services:
  - name: docker:24.0.5-dind

variables:
  APPLICATION_NAME: weight
  CONTAINER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_SHORT_SHA}
  K8S_INGRESS_HOST: api.weight.home.maximemoreillon.com

build:
  stage: build
  only:
    - master
  tags:
    # - dind
    - k8s
  script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin;
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag  ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_TAGGED}

deploy:
  stage: deploy
  only:
    - master
  tags:
    # - dind
    - k8s
  before_script:
    - kubectl config use-context moreillon_ci/moreillon_k8s_home/kubernetes-agent:home
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -n ${KUBERNETES_NAMESPACE} -f -
