stages:
  - containerization
  - deploy

variables:
  APPLICATION_NAME: weight
  DOCKER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  CERTIFICATE_DOMAIN: api.weight.maximemoreillon.com


containerization:
  stage: containerization
  tags:
    - moreillon
  script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin;
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}
    - docker image rm ${DOCKER_IMAGE}

deployment:
  stage: deploy
  script:
    - envsubst < deployment.yml | kubectl apply -f -
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
